apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sock-shop

generatorOptions:
  disableNameSuffixHash: true

sortOptions:
  order: fifo

resources:
  - 09-front-end-dep.yaml
