apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-temp-pvc
  namespace: sock-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client